# Dockerfile used for creating a container capable to run AcmeAir monolithic
# Must be running on the same network as the mongodb container
#FROM icr.io/appcafe/open-liberty:beta-instanton
#FROM open-liberty:kernel-slim-java17-openj9
#FROM open-liberty:17_2023.05.05
FROM icr.io/appcafe/open-liberty:full-java17-openj9-ubi

COPY --chown=1001:0 LibertyFiles/server.xml /config/server.xml
COPY --chown=1001:0 LibertyFiles/acmeair-java-2.0.0-SNAPSHOT.war /config/apps/
EXPOSE 9080

#ENV OPENJ9_SCC=false
# The following e environment variables are used for JTServer AOT ccahe support
#ENV OPENJ9_JAVA_OPTIONS="-XX:+IgnoreUnrecognizedVMOptions -XX:+IdleTuningGcOnIdle -Xshareclasses:name=openj9_system_scc,cacheDir=/opt/java/.scc,nonFatal -Dosgi.checkConfiguration=false"`
#ENV TRIM_SCC=false
#ENV SCC_SIZE=150m

ENV VERBOSE=true
RUN configure.sh

