apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: acmeair-baseline
  namespace: scc-[Your_initial]
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: acmeair-baseline
      annotations:
        # This is what we say that a single pod should be able to handle.
        autoscaling.knative.dev/target: "20"
        # Agregate the metrics over 30 seconds
        autoscaling.knative.dev/window: "30s"
        # wait 120 seconds at reduced concurrency before a scale-down decision is applied.
        autoscaling.knative.dev/scale-down-delay: "120s"
        # Scale up to 2 pods
        autoscaling.knative.dev/max-scale: "2"
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/scc-[Your_initial]/liberty-acmeair-ee8:23.0.0.6
        imagePullPolicy: Always
        name: acmeair-baseline
        env:
        - name: JVM_ARGS
          value: ""
        - name: MONGO_HOST
          value: "mongodb"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_DBNAME
          value: "acmeair"
        ports:
        - containerPort: 9080
        resources:
          requests:
            memory: "512Mi"
            cpu: "1000m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /
            port: 9080
          initialDelaySeconds: 5
          periodSeconds: 1
          failureThreshold: 10


